apiVersion: v1
kind: Service
metadata:
  labels:
    service: dotcms
  name: dotcms
spec:
  ports:
    - name: "8082" 
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: "8443" 
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    service: dotcms
