apiVersion: v1
kind: Service
metadata:
  labels:
    service: opensearch
  name: opensearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9600"
      port: 9600
      targetPort: 9600
  selector:
    service: opensearch
status:
  loadBalancer: {}
